### ISSUE TITLE
config.authentication.encryption.key bytes error

### ISSUE THREAD

**Issue by chuckan13** [deepforge-dev/deepforge#1720]
When cloning this repository and then running npm install inside of it, I get this error: 
`In configuration: config.authentication.encryption.key must be 32 bytes. Got: 33 bytes`

**Comment by umesh-timalsina** [comment]
Can you post your platform on which you are running your npm script?

**Comment by chuckan13** [comment]
Windows 10. Is that what you mean by platform?

**Comment by brollb** [comment]
Hi @chuckan13, thanks for reaching out!

I believe this specific issue is caused by Windows-style line endings in the webgme-engine dependency (specifically [here](https://github.com/webgme/webgme-engine/pull/200/files#diff-f2efe15a55b744be1de57bdd1e7a71dd)). 

There are two possible solutions (#2 is recommended):
1. Add the following to `config/config.base.js`:
```javascript
config.authentication.encryption.key = 'pathToAnotherFileWith32bytes';
```
Although this approach should address the immediate issue, there may be other issues with running the deepforge server on Windows as it is tested on Linux. If Windows support for the server is important (and you don't mind providing feedback or contributing), I would be happy to provide guidance for exploring Windows support :)

2. Run deepforge in a docker container. This is the preferred way of running DeepForge in production and should work on Windows as well. If you have [docker-compose](https://docs.docker.com/compose/) installed, you can simply download the [docker-compose.yaml file](https://github.com/deepforge-dev/deepforge/blob/master/docker/docker-compose.yml) and start it with `docker-compose up`.

**Comment by umesh-timalsina** [comment]
Mean while you can run a server from docker using the following compose file with `docker-compose up`
```
---
version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "$HOME/.deepforge/data:/data/db"
  server:
    environment:
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "DEEPFORGE_HOST=http://127.0.0.1"
      - "NODE_ENV=default"
    image: deepforge/kitchen-sink:latest
    ports:
      - "8888:8888"
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
    depends_on:
      - mongo
    entrypoint: ['npm', 'start']
```
